server:
  port: 8081
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootdemoacem@gmail.com
    password: zlgpfgnxwpzwjooq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true